### ISSUE TITLE
Error when trying to search a string column 

### ISSUE THREAD

**Issue by chirislash** [mcintyre321/mvc.jquery.datatables#145] opened 2016-04-25 21:24 UTC
I have a column called PO-Number which returns string Data with the format [0-9]'-'[0-9].
When I search by the first number it works fine but when I add the minus and a number it crashes and throw me this error
Do I have to add some validation or I am missing something?
![image](https://cloud.githubusercontent.com/assets/11575247/14799330/3381550a-0af9-11e6-9acc-cfde5cb6fb77.png)

**Comment by mcintyre321** [comment] 2016-04-26 15:12
I haven't seen this issue before.

The best thing to do is to fork the project, and add a similar case to the example project. If you can repeat the problem there, then I can debug it myself.

You can also post full stack trace, your ViewModel type and maybe a copy of the posted DataTablesParam?

**Comment by chirislash** [comment] 2016-04-26 19:32
I've Just created a new project and installed the library via nuget package (version 1.3.34)
I created a table and added dummy data.
When you try to search via the PO-Number Column or the date columns I get the same issue.
For example when I try to search 1-1 or 26/4.
Just run the Index in home controller.

I uploaded it in my repository https://github.com/chirislash/Mvc.DataTablesSample

**Comment by mcintyre321** [comment] 2016-04-28 10:56
Interestingly this is being caused by searching for a string which can be parsed into a DateTime e.g. 1-1 is parsed as 1/Jan 20116. If you do search for 1-1 in the multi-column search you will only get stuff from that date! Still investigating...

**Comment by chirislash** [comment] 2016-04-28 17:06
Is there a DataTableParam to indicate that the column wich contains the PO-Number is a string?
Or the DateTime columns are in the format dd/mm/yyyy
I tried with this in the JavaScript:
"aoColumns": [
      { "sType": "numeric" },
      { "sType": "string" },
      { "sType": "string" },
      { "sType": "string" },
      { "sType": "string" },
	  { "sType": "string" },
      { "sType": "string" },
      { "sType": "date" },
      { "sType": "date" },
      { "sType": "string" },
	  { "sType": "string" }
    ]
But it didn't seem to work

**Comment by mcintyre321** [comment] 2016-04-29 08:23
I'll be pushing a fix for this in the next couple of days - in the meantime
you could set [DataTables(Searcheable = false)] on the datetime properties.
I'll update this issue when the fix is ready.

**Comment by chirislash** [comment] 2016-04-29 14:15
It's ok and thanks for the support :v:  :octocat:

**Comment by mcintyre321** [comment] 2016-04-29 14:19
No problemo!

**Comment by mcintyre321** [comment] 2016-04-29 14:20
(Better keep this open as a reminder for pushing the fix)

**Comment by mcintyre321** [comment] 2016-04-30 13:18
This is fixed now, please update your packages.

**Closed by mcintyre321** 2016-04-30 13:18 UTC

**Comment by chirislash** [comment] 2016-05-02 12:35
Thanks man you are awesome!
